### ISSUE TITLE
Add taxation to shops

### ISSUE THREAD

**Issue by Sven65** [Sven65/Slabbo#72]
**Please describe your feature request**

Server admins and players with the proper permission node should be able to set the tax of an individual shop.

The tax should be paid by the seller, and be settable with a command, if the shop owner has the permission node.

There should be an option in config.yml to set the default tax, and where the money should go by default. Either to a player, or if it should be voided.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sudojunior** [comment]
_Thought process, trying to understand the brief._

### Command options

- `/slabbo modify tax <amount:0..100f>`
  - `?isLookingAt`
  - `!hasPermission`

### Permission nodes

- `slabbo.modify.(self|others).tax` - set tax of a shop with appropriate access
  - `self` - allow shop owner to modify shop tax (... what?)
  - `others` - allow 'others' to modify tax of a shop

## Configuration

```yaml
defaults:
  # config layouts

  # flat
  tax: 0 # 0..100 - {x}% tax on all shops
  tax_man: "{name}" # or nil - the latter would void the collected money

  # nested
  tax:
    amount: 0
    collector/funnel/recipient: "{name}" # or nil
```
